local myIcons       = {
    Text            = ' ',
    Method          = ' ',
    Function        = ' ',
    Constructor     = ' ',
    Field           = 'ﰠ ',
    Variable        = ' ',
    Class           = ' ',
    Interface       = 'ﳤ ',
    Module          = ' ',
    Property        = '襁',
    Unit            = '塞',
    Value           = ' ',
    Keyword         = ' ',
    Snippet         = ' ',
    Color           = ' ',
    Enum            = '練',
    File            = ' ',
    Reference       = ' ',
    Folder          = ' ',
    EnumMember      = 'ﴯ ',
    Constant        = ' ',
    Struct          = 'פּ ',
    Event           = ' ',
    Operator        = ' ',
    TypeParameter   = ' ',
}

local vistaIcons = {
  ["func"] = ' ',
  ["function"] = ' ',
  ["functions"] = ' ',
  ["var"] = ' ',
  ["variable"] = ' ',
  ["const"] = ' ',
  ["constant"] = ' ',
  ["method"] = ' ',
  ["packages"] = ' ',
  ["package"] = ' ',
  ["enum"] = ' ',
  ["enummember"] = ' ',
  ["enumerator"] = ' ',
  ["modules"] = "\uF136",
  ["module"] = "\uF136",
  ["type"] = ' ',
  ["typedef"] = ' ',
  ["types"] = ' ',
  ["field"] = ' ',
  ["fields"] = ' ',
  ["macro"] = ' ',
  ["macros"] = ' ',
  ["map"] = 'פּ ',
  ["class"] = ' ',
  ["augroup"] = 'פּ ',
  ["struct"] = ' ',
  ["union"] = '鬒',
  ["member"] = ' ',
  ["target"] = ' ',
  ["property"] = '襁',
  ["interface"] = '',
  ["namespace"] = ' ',
  ["subroutine"] = '羚',
  ["implementation"] = ' ',
  ["typeParameter"] = ' ',
  ["default"] = ' ',
}


local kindDefaults = {
  -- if you change or add symbol here
  -- replace corresponding line in readme
  Text = "",
  Method = "",
  Function = "",
  Constructor = "",
  Field = "ﰠ",
  Variable = "",
  Class = "ﴯ",
  Interface = "",
  Module = "",
  Property = "ﰠ",
  Unit = "塞",
  Value = "",
  Enum = "",
  Keyword = "",
  Snippet = "",
  Color = "",
  File = "",
  Reference = "",
  Folder = "",
  EnumMember = "",
  Constant = "",
  Struct = "פּ",
  Event = "",
  Operator = "",
  TypeParameter = "",
}

local kindCodicons = {
  Text = "",
  Method = "",
  Function = "",
  Constructor = "",
  Field = "",
  Variable = "",
  Class = "",
  Interface = "",
  Module = "",
  Property = "",
  Unit = "",
  Value = "",
  Enum = "",
  Keyword = "",
  Snippet = "",
  Color = "",
  File = "",
  Reference = "",
  Folder = "",
  EnumMember = "",
  Constant = "",
  Struct = "",
  Event = "",
  Operator = "",
  TypeParameter = "",
}

local symbolsOutlineIcons = {}

local symbolsTodo = {
  symbols = {
    File = { icon = "", hl = "@text.uri" },
    Module = { icon = "", hl = "@namespace" },
    Namespace = { icon = "", hl = "@namespace" },
    Package = { icon = "", hl = "@namespace" },
    Class = { icon = "𝓒", hl = "@type" },
    Method = { icon = "ƒ", hl = "@method" },
    Property = { icon = "", hl = "@method" },
    Field = { icon = "", hl = "@field" },
    Constructor = { icon = "", hl = "@constructor" },
    Enum = { icon = "ℰ", hl = "@type" },
    Interface = { icon = "ﰮ", hl = "@type" },
    Function = { icon = "", hl = "@function" },
    Variable = { icon = "", hl = "@constant" },
    Constant = { icon = "", hl = "@constant" },
    String = { icon = "𝓐", hl = "@string" },
    Number = { icon = "#", hl = "@number" },
    Boolean = { icon = "⊨", hl = "@boolean" },
    Array = { icon = "", hl = "@constant" },
    Object = { icon = "⦿", hl = "@type" },
    Key = { icon = "🔐", hl = "@type" },
    Null = { icon = "NULL", hl = "@type" },
    EnumMember = { icon = "", hl = "@field" },
    Struct = { icon = "𝓢", hl = "@type" },
    Event = { icon = "🗲", hl = "@type" },
    Operator = { icon = "+", hl = "@operator" },
    TypeParameter = { icon = "𝙏", hl = "@parameter" },
    Component = { icon = "", hl = "@function" },
    Fragment = { icon = "", hl = "@constant" },
  },
}

return {
  icons = myIcons,
  vistaIcons = vistaIcons,
  symbolsIcons = symbolsOutlineIcons,
  kindIcons = kindDefaults,
  codicons = kindCodicons,
}
